import { StyleSheet } from "@react-pdf/renderer"
import { BRAND_COLORS } from "@/lib/brand"

/** Seamcor brand tokens for React-PDF (mirrors site primary / accent). */
export const PDF_COLORS = {
  primary: BRAND_COLORS.navy,
  accent: BRAND_COLORS.pink,
  text: "#334155",
  muted: BRAND_COLORS.slate,
  border: "#E2E8F0",
  rowAlt: BRAND_COLORS.offWhite,
  white: "#FFFFFF",
  summaryBg: "#F1F5F9",
} as const

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 9,
    fontFamily: "Helvetica",
    lineHeight: 1.45,
    color: PDF_COLORS.text,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 7,
    color: PDF_COLORS.muted,
  },
  logo: { width: 320, marginBottom: 10 },
  headerRule: {
    height: 2,
    backgroundColor: PDF_COLORS.primary,
    marginBottom: 14,
  },
  docTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
    marginBottom: 2,
  },
  docMeta: { fontSize: 9, color: PDF_COLORS.muted, marginBottom: 12 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
    marginTop: 14,
    marginBottom: 6,
  },
  customerName: {
    fontSize: 11,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
    marginBottom: 4,
  },
  customerLine: { fontSize: 9, marginBottom: 2 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: PDF_COLORS.primary,
    color: PDF_COLORS.white,
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontSize: 8,
    fontWeight: "bold",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: PDF_COLORS.border,
    fontSize: 8,
  },
  tableRowAlt: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: PDF_COLORS.border,
    backgroundColor: PDF_COLORS.rowAlt,
    fontSize: 8,
  },
  tableFooter: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: PDF_COLORS.summaryBg,
    fontSize: 8,
    fontWeight: "bold",
  },
  colItem: { flex: 3 },
  colPrice: { flex: 2, textAlign: "right" },
  colQty: { flex: 0.6, textAlign: "center" },
  colTotal: { flex: 1.2, textAlign: "right" },
  itemSub: { fontSize: 7, color: PDF_COLORS.muted, marginTop: 2 },
  summaryBox: {
    marginTop: 16,
    alignSelf: "flex-end",
    width: 240,
    padding: 10,
    backgroundColor: PDF_COLORS.summaryBg,
    borderWidth: 0.5,
    borderColor: PDF_COLORS.border,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
    fontSize: 9,
  },
  summaryGrand: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.primary,
    fontSize: 10,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
  },
  termsStrip: {
    marginTop: 14,
    padding: 10,
    backgroundColor: PDF_COLORS.rowAlt,
    borderLeftWidth: 3,
    borderLeftColor: PDF_COLORS.accent,
  },
  termsBullet: { fontSize: 8, marginBottom: 3 },
  label: { fontWeight: "bold" },
  detailRow: { marginBottom: 3, fontSize: 9 },
  h2: {
    fontSize: 11,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
    marginTop: 12,
    marginBottom: 4,
  },
  tcTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
    marginBottom: 6,
  },
  tcHeading: {
    fontSize: 9,
    fontWeight: "bold",
    color: PDF_COLORS.primary,
    marginTop: 8,
    marginBottom: 3,
  },
  tcPara: { fontSize: 7.5, marginBottom: 4, textAlign: "justify", lineHeight: 1.35 },
})
