steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - -f
      - Dockerfile
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/exalted-splicer-499401-e2/seamvex/documenso:latest
timeout: 3600s
